### ISSUE TITLE
pyrotech or minecolony's 

### ISSUE THREAD

**Issue by Seilican** [kreezxil/Bane-of-Dragons#10]
# Mod Nominated for Removal
Mod Name:

pyrotech or minecolony's 

# Reason for Nomination
pyrotech is a very good looking mod that makes early game harder than even late game things line getting wood plank's so you do not want to stop an build a base

minecolony's is all about building a base and using a normal progression so it becomes not worth doing other than a Ha i could over come not that its helpful if pyrotech is in game
  
Reason:

no way at this time to auto make plank's

**Comment by kreezxil** [comment]
I'm going to need a better reason to remove minecolonies.

Minecolonies would essentially be a side quest, because Bane of Dragons is about exploration and conquering 8 legendary dragons. QUEST LINES wip FOR THAT.

Pyrotech exists to slow down the player that doesn't want to play the pack as it is designed but not prohibit them otherwise.

**Comment by Seilican** [comment]
Pyrotech is stopping minecolony's ways to work with the new steps to make many things like planks and wooden tools

**Comment by kreezxil** [comment]
ok, I'll remove minecolonies then.
