### ISSUE TITLE
[please fix] Mine and slash portal crashes server

### ISSUE THREAD

**Issue by jam325** [kreezxil/Bane-of-Dragons#12]
**Describe the bug**

**To Reproduce**
1. Go to 'portal'

**Screenshots**

**Versions:**

 - Minecraft:1.12.2
 - Forge:14.23.5.2847
 - Mod Pack :
 - Mod Name:Mine and slash
 - Mod Version:1.7.0

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: 
Debug Log:
Latest Log:

**Additional context**

**Comment by AzureDoom** [comment]
I see no crash log, please attach a crash log.

**Comment by kreezxil** [comment]
@jam325 whose server mine or yours? reporting my crashes don't help too much because you don't have access to the logs. But if it's your server or client you do have access to the logs and need to attach them.

The proper way to do it when referring to my servers is to report it in the community for World of Dragons and describe in detail how you did it. Then I or my admin will access the crash reports and other log files, possibly asking you more questions in the process and then creating a formal bug report that the mod author can actually use.

Also the report you filed was filled out very badly. You should always delete elements that are not relevant to what you are reporting vs leaving them there.

I'm going to close this now because I think you are reporting a crash that has occurred on my server.

**Comment by kreezxil** [comment]
@AzureZhen The following are the server crash reports. However M&S isn't the culprit from what I can see but instead Recurrent Complex. Then again RC is referenced so far down into the trace it feels like it might not be the actual bug either. What do you think?

https://gist.github.com/c70887b06cb3a42e2afe29eb1af5478d
https://gist.github.com/b8f234b60dbf08332d0cc2efbdfef9d2
https://gist.github.com/7c95ced1b201ad95c476f38cd8877cbf
https://gist.github.com/cfacac86e984b316a9098e3fcf24ac8e
https://gist.github.com/437447350f8a202b692d9393eb8efecf

**Comment by kreezxil** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/412

Seeing that Recurrent Complex stopped any semblance of development and bug processing back in February of 2019, my only choice is to remove it to fix this issue.

**Comment by AzureDoom** [comment]
Does seem to be Recurrent Complex issues.

**Comment by kreezxil** [comment]
i see no update the RC. i'm removing it and that should resolve these issues.
